CREATE SEQUENCE SEQ_PHONEBOOK START WITH 1;

CREATE TABLE TBL_PHONEBOOK (
	NAME VARCHAR2(255) NOT NULL,
	PHONE_NUMBER VARCHAR2(1000) NOT NULL,
	AGE NUMBER,
	BIRTHDATE DATE,
	CONSTRAINT PK_PHONEBOOK PRIMARY KEY(NAME, PHONE_NUMBER)
);

DROP TABLE TBL_PHONEBOOK;

INSERT INTO TBL_PHONEBOOK (NAME, PHONE_NUMBER, AGE, BIRTHDATE)
VALUES ('조남호', '01034536448', 23, '2000-02-02');

SELECT NAME, PHONE_NUMBER, AGE, TO_CHAR(BIRTHDATE, 'YYYY-MM-DD') FROM TBL_PHONEBOOK ORDER BY NAME, PHONE_NUMBER;

DELETE FROM TBL_PHONEBOOK tp WHERE NAME = '조남호';

UPDATE TBL_PHONEBOOK SET AGE = 24, BIRTHDATE = '1999-02-02'
WHERE NAME = '조남호' AND PHONE_NUMBER = 1036316448;


SELECT PHONE_NUMBER FROM TBL_PHONEBOOK WHERE NAME = '조남호';