CREATE SEQUENCE SEQ_POST;

CREATE TABLE TBL_POST(
   ID NUMBER CONSTRAINT PK_POST PRIMARY KEY,
   POST_TITLE VARCHAR2(1000) NOT NULL,
   POST_CONTENT VARCHAR2(1000) NOT NULL,
   MEMBER_ID NUMBER,
   CONSTRAINT FK_POST_ FOREIGN KEY(MEMBER_ID)
   REFERENCES TBL_MEMBER(ID)
);

SELECT * FROM TBL_POST;

INSERT INTO TBL_POST
(ID, POST_TITLE, POST_CONTENT, MEMBER_ID)
VALUES(SEQ_POST.NEXTVAL, '테스트 제목1', '테스트 내용1', 3);

SELECT POST_TITLE, M.MEMBER_NAME
FROM TBL_POST P
JOIN TBL_MEMBER M
ON P.MEMBER_ID = M.ID;

SELECT POST_TITLE, POST_CONTENT, M.MEMBER_NAME FROM TBL_POST P JOIN TBL_MEMBER M 
ON P.MEMBER_ID = M.ID 
WHERE P.ID = 44;

UPDATE TBL_POST SET POST_TITLE, POST_CONTENT
WHERE ID = ?

SELECT P.ID, POST_TITLE, M.MEMBER_NAME FROM TBL_POST P 
JOIN TBL_MEMBER M ON P.MEMBER_ID = M.ID;

SELECT P.ID, POST_TITLE, POST_CONTENT, M.MEMBER_ID, M.MEMBER_NAME
FROM TBL_MEMBER M JOIN TBL_POST P ON M.ID = P.MEMBER_ID AND P.ID = 44;

SELECT P.ID, P.POST_TITLE, P.POST_CONTENT, M.MEMBER_ID, M.MEMBER_NAME, COUNT(R.ID) AS REPLY_COUNT
FROM TBL_POST P
LEFT OUTER JOIN TBL_REPLY R ON P.ID = R.POST_ID
JOIN TBL_MEMBER M ON P.MEMBER_ID = M.ID
GROUP BY P.ID, P.POST_TITLE, P.POST_CONTENT, M.MEMBER_ID, M.MEMBER_NAME;