CREATE TABLE TBL_REPLY(
   ID NUMBER CONSTRAINT PK_REPLY PRIMARY KEY,
   REPLY_CONTENT VARCHAR2(1000) NOT NULL,
   POST_ID NUMBER NOT NULL,
   MEMBER_ID NUMBER NOT NULL,
   CONSTRAINT FK_REPLY_POST FOREIGN KEY(POST_ID)
   REFERENCES TBL_POST(ID),
   CONSTRAINT FK_REPLY_MEMBER FOREIGN KEY(MEMBER_ID)
   REFERENCES TBL_MEMBER(ID)
);

CREATE SEQUENCE SEQ_REPLY START WITH 1;
DROP SEQUENCE SEQ_REPLY;

SELECT * FROM TBL_REPLY;

SELECT M.MEMBER_NAME, R.REPLY_CONTENT
FROM TBL_REPLY R
JOIN TBL_MEMBER M
ON M.ID = R.MEMBER_ID
WHERE POST_ID = 44;

UPDATE TBL_REPLY SET REPLY_CONTENT = ?
WHERE ID = ?
AND MEMBER_ID = ?;

SELECT COUNT(ID) FROM TBL_REPLY;