CREATE TABLE TBL_MEMBER(
	ID NUMBER CONSTRAINT PK_MEMBER PRIMARY KEY,
	MEMBER_ID VARCHAR2(1000) NOT NULL,
	MEMBER_PASSWORD VARCHAR2(1000) NOT NULL,
	MEMBER_NAME VARCHAR2(1000) NOT NULL,
	MEMBER_ADDRESS VARCHAR2(1000) NOT NULL,
	MEMBER_RECOMMENDER_ID VARCHAR2(1000)
);

CREATE SEQUENCE SEQ_MEMBER;

INSERT INTO SCOTT.TBL_MEMBER
(ID, MEMBER_ID, MEMBER_PASSWORD, MEMBER_NAME, MEMBER_ADDRESS)
VALUES(SEQ_MEMBER.NEXTVAL, 'hds1234', '1234', '한동석', '경기도 남양주시');

SELECT ID, MEMBER_ID, MEMBER_PASSWORD, MEMBER_NAME, MEMBER_ADDRESS, COALESCE(MEMBER_RECOMMENDER_ID, '없음') AS 추천인
FROM TBL_MEMBER
ORDER BY ID;

SELECT MEMBER_NAME
FROM TBL_MEMBER
WHERE MEMBER_RECOMMENDER_ID IN (SELECT MEMBER_ID FROM TBL_MEMBER WHERE ID = 1)
GROUP BY MEMBER_NAME;

SELECT COUNT(MEMBER_RECOMMENDER_ID)
FROM TBL_MEMBER
WHERE MEMBER_RECOMMENDER_ID IN (SELECT MEMBER_ID FROM TBL_MEMBER WHERE ID = 1)
GROUP BY MEMBER_RECOMMENDER_ID;

SELECT MEMBER_NAME
FROM TBL_MEMBER
WHERE MEMBER_ID =
(
    SELECT MEMBER_RECOMMENDER_ID
    FROM TBL_MEMBER
    WHERE ID = 3
);

SELECT P.ID, M.ID FROM TBL_POST P
JOIN TBL_MEMBER M 
ON P.MEMBER_ID = M.ID
WHERE P.ID = 44;