CREATE TABLE TBL_DEPARTMENT (
	ID NUMBER CONSTRAINT PK_DEPARTMENT PRIMARY KEY,
	DEPARTMENT_NAME VARCHAR2(255) NOT NULL,
	ALLOCATED_NUMBER NUMBER DEFAULT 0 
);

CREATE TABLE TBL_MEMBER (
	ID NUMBER CONSTRAINT PK_MEMBER PRIMARY KEY,
	MEMBER_NAME VARCHAR2(255) NOT NULL,
	DEPARTMENT_ID NUMBER,
	CONSTRAINT RK_MEMBER_DEPARTMENT FOREIGN KEY (DEPARTMENT_ID)
	REFERENCES TBL_DEPARTMENT(ID)
);

CREATE TABLE TBL_PROJECT (
	MEMBER_ID NUMBER,
	PROJECT_CODE VARCHAR2(10),
	PROJECT_SALARY NUMBER DEFAULT 0,
	CONSTRAINT PK_PROJECT PRIMARY KEY (MEMBER_ID, PROJECT_CODE),
	CONSTRAINT RK_PROJECT_MEMBER FOREIGN KEY (MEMBER_ID)
	REFERENCES TBL_MEMBER(ID)
);